version: "3.9"

services: 
#   alpine:
#     build:
#       context: Alpine/
#       dockerfile: Dockerfile
#     expose:
#       - "22"
#     ports:
#       - "4848:22"
#     volumes:
#       - linux2-lab-data:/home/zephyro/code
  
  ubuntu:
    build:
      context: Ubuntu/
      dockerfile: Dockerfile
    expose:
      - "22"
    ports:
      - "2222:22"
    volumes:
      - ubuntu-data:/home

volumes:
  linux2-lab-data:
    name: "linux2-lab-data"
  ubuntu-data:
    name: "ubuntu-data"

