---
all:
  vars:
    ansible_user: deploy
    ansible_ssh_private_key: ~/.ssh/deploy_id_rsa
    ansible_become: yes
    ansible_become_user: root
    ansible_become_method: sudo

    node_exporter_port: 9100
    apache_exporter_port: 9117
    mysql_exporter_port: 9004

  hosts:
    web:
      ansible_host: 172.28.128.180
    db:
      ansible_host: 172.28.128.132
    grafana:
      ansible_host: 172.28.128.69
    prometheus:
      ansible_host: 172.28.128.69

  children:
    metrics:
      grafana:
      prometheus:
