---
- name: Assert latest packages installed
  ansible.builtin.yum:
    name:
      - mariadb-server
      - MySQL-python
    state: latest

- name: Start MariaDB on boot
  ansible.builtin.service:
    name: mariadb
    enabled: yes
    state: started

- name: Create DB-User
  no_log: true
  ansible.builtin.mysql_user:
    host: "{{ web_ip }}"
    name: "{{ db_user }}"
    password: "{{ db_user_pwd }}"
    priv: '{{ db_name }}.*:ALL'
    state: present

- name: Create database
  ansible.builtin.mysql_db:
    name: "{{ db_name }}"
    state: present
